<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>ListHero-Web-c1e1d3f1-1f12-435d-b397-30b3cb4dc50d</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../ListHero.UI/ListHero.UI.csproj" />
    <ProjectReference Include="../ListHero.Client.Api/ListHero.Client.Api.csproj" />
    <PackageReference Include="Microsoft.Identity.Web" />
    <PackageReference Include="Microsoft.Identity.Web.UI" />
  </ItemGroup>
</Project>